In [1]:
import numpy as np

In [3]:
# X = np.array([[1, 1], [2, 1], [3, 1.2], [4, 1], [5, 0.8], [6, 1]])
from sklearn.decomposition import NMF
model = NMF(n_components=5, init='random', random_state=0)
print(model)
# W = model.fit_transform(X)
# print(W)
# H = model.components_
# print(H)

NMF(init='random', n_components=5, random_state=0)


In [ ]:
X_new = np.array([[1, 0], [1, 6.1], [1, 0], [1, 4], [3.2, 1], [0, 4]])
W_new = model.transform(X_new)


In [ ]:
x_new1 = model.transform(X_new)
print(x_new1)

In [ ]:
print(W_new)

In [5]:
from sklearn.datasets import load_digits
from sklearn.decomposition import FastICA
X, _ = load_digits(return_X_y=True)
print(X)
transformer = FastICA(n_components=7,random_state=0)
X_transformed = transformer.fit_transform(X)
X_transformed.shape

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


/home/amrgaballah/anaconda3/lib/python3.8/site-packages/sklearn/decomposition/_fastica.py:118: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  warnings.warn('FastICA did not converge. Consider increasing '


(1797, 7)